result/urls.py
from django.urls import path, re_path

from .views import *


app_name = 'result'


urlpatterns = [
    path('add-subject', add_subject, name='add-subject'),
    path('subject-list', subject_list, name='subject-list'),
    path('mark-entry', mark_entry, name='mark-entry'),
    #path('mark-entry-mid-term', mark_entry_mid_term, name='mark-entry-mid-term'),
    path('result-preview', pin_check, name='result-preview'),
    #path('result-preview-mid-term', pin_check_mid_term, name='result-preview-mid-term'),
    re_path(r'mid-term-result/(?P<reg_no>[\w/]+)/$', student_mid_term_result, name="student-mid-term-result"),
    re_path(r'print/(?P<level>[\w-]+)/(?P<term>[\w\s\w]+)/(?P<year>[\w/]+)/$', print_write_pdf_view, name="print"),
    re_path(r'download/(?P<level>[\w-]+)/(?P<term>[\w\s\w]+)/(?P<year>[\w/]+)/$', download_write_pdf_view, name="download"),
    #path('print/<level>/<term>/<year>', print_write_pdf_view, name='print'),
    #path('download/<level>/<term>/<year>', download_write_pdf_view, name='download'),
    path('mark-table/<subject>', mark_table, name='mark-table'),

]

schoolmanagement/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .views import home_page, preview
import teacher.views as views
import student.views as student_views
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

import django.contrib.auth.views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('preview/', preview, name='preview'),
    path('', include('administration.urls')),
    #re_path(r'classroom-delete/(?P<class_name>[\w/]+)/$', views.create_class_delete, name="classroom-delete"),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('academic/', include('academic.urls')),
    path('employee/', include('employee.urls')),
    path('result/', include('result.urls')),
    path('address/', include('address.urls')),
    path('account/', include('account.urls')),
    path('attendance/', include('attendance.urls')),
    re_path(r'password_change/(?P<username>[\w/]+)/$', student_views.change_password, name="password_change"),
    #path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('class-wise-student-registration', views.class_wise_student_registration, name='class-wise-student-registration'),
    path('students-excel-format', views.export_students_registration_xls, name='export_students_registration_xls'),
    #re_path(r'student-registration/(?P<name_teacher>[\w\s\w]+)/$', views.student_registration, name="student-registration"),
    path('student-registration', views.student_registration, name='student-registration'),
    path('student-list', views.student_list, name='student-list'),
    path('teacher-upload/', views.excell_student_registration, name='excell_student_registration'),
    re_path(r'student-list/(?P<username>[\w/]+)/$', views.student_list, name='student-list-re'),
    path('student-list-search', views.student_list_search, name='student-list-search'),
    #path('student-list2', views.student_list2, name='student-list2'),
    #path('student-result', views.student_result, name='student-result'),
    re_path(r'student-result/(?P<reg_no>[\w/]+)/$', views.student_result, name="student-result"),

    re_path(r'student-edit-edit/(?P<username>[\w/]+)/$', views.student_edit, name="student-edit-edit"),
    re_path(r'student-delete/(?P<username>[\w/_]+)/$', views.student_delete, name="student-delete"),
    re_path(r'student-upload-result/(?P<reg_no>[\w/]+)$', views.student_upload_result, name="student-upload-result"),
    re_path(r'profile/(?P<reg_no>[\w/]+)/$', views.student_profile, name="student-profile"),
    re_path(r'restore-student-re/(?P<username>[\w/_]+)/$', views.restore_student_re, name="restore-student-re"),
    #path('edit/<reg_no>', views.student_edit, name='student-edit'),
    # re_path(r'edit/(?P<reg_no>[\w/]+)/$', views.student_edit, name="student-edit"),
    #path('delete/<reg_no>', views.student_delete, name='student-delete'),
    re_path(r'delete/(?P<reg_no>[\w/]+)/$', views.result_delete, name="result-delete"),
    re_path(r'student-search/(?P<clas>[\w]+)/$', views.student_search, name='student-search'),
    path('enrolled/', views.enrolled_student, name='enrolled-student'),
    path('deleted-students', views.deleted_students, name='deleted-students'),
    re_path(r'deleted-students/(?P<username>[\w/_]+)/$', views.deleted_students, name="deleted-students-re"),
    #path('enrolled-student/<reg>', views.student_enrolled, name='enrolled'),
    re_path(r'enrolled-student/(?P<reg>[\w/]+)/$', views.student_enrolled, name="enrolled"),
    path('enrolled-student-list/', views.enrolled_student_list, name='enrolled-student-list'),
]

student/models.py
from django.db import models
import random
from django.contrib.auth.models import User

from academic.models import ClassInfo, ClassRegistration
from address.models import District, Upazilla, Union
from django.core.validators import FileExtensionValidator
from administration.models import *



class PersonalInfo(models.Model):
    first_name = models.CharField(max_length=45, null=True, blank=True,)
    last_name = models.CharField(max_length=45, null=True, blank=True,)
    pass_word = models.CharField(max_length=45, null=True, blank=True,)
    class_of_student = models.ForeignKey(ClassInfo, default='', on_delete=models.CASCADE, related_name="class_of_students",)
    user = models.ForeignKey(User, default='', on_delete=models.CASCADE, related_name="user_student",)
    photo = models.ImageField(upload_to='student-photos/', null=True, blank=True,)
    blood_group_choice = (
        ('a+', 'A+'),
        ('o+', 'O+'),
        ('b+', 'B+'),
        ('ab+', 'AB+'),
        ('a-', 'A-'),
        ('o-', 'O-'),
        ('b-', 'B-'),
        ('ab-', 'AB-')
    )
    blood_group = models.CharField(choices=blood_group_choice, max_length=5, null=True, blank=True,)
    date_of_birth = models.DateField(null=True, blank=True,)
    gender_choice = (
        ('male', 'Male'),
        ('female', 'Female')
    )
    gender = models.CharField(choices=gender_choice, max_length=10, null=True, blank=True,)
    phone_no = models.CharField(max_length=11, null=True, blank=True,)
    email = models.EmailField(blank=True, null=True)
    birth_certificate_no = models.IntegerField(null=True, blank=True,)
    religion_choice = (
        ('Islam', 'Islam'),
        ('Christianity', 'Christianity')
    )
    religion = models.CharField(choices=religion_choice, max_length=45, null=True, blank=True,)
    nationality_choice = (
        ('Ghana', 'Ghana'),
        ('Nigeria', 'Nigeria')
    )
    nationality = models.CharField(choices=nationality_choice, max_length=45, null=True, blank=True,)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"






class AcademicInfo(models.Model):
    class_info = models.ForeignKey(ClassInfo, on_delete=models.CASCADE, blank=True, null=True, related_name="student_class")
    registration_no = models.CharField(max_length=100, unique=True, null=True, blank=True,)
    #     ('not enroll', 'Not Enroll'),
    #     ('enrolled', 'Enrolled'),
    #     ('regular', 'Regular'),
    #     ('irregular', 'Irregular'),
    #     ('passed', 'Passed'),
    # )
    # status = models.CharField(choices=status_select, default='not enroll', max_length=15, null=True, blank=True,)
    personal_info = models.ForeignKey(PersonalInfo, on_delete=models.CASCADE, null=True, blank=True, related_name="student_persona")
    result = models.ForeignKey(Result, on_delete=models.CASCADE, null=True, blank=True, related_name="student_result")
    # address_info = models.ForeignKey(StudentAddressInfo, on_delete=models.CASCADE, null=True, blank=True,)
    # guardian_info = models.ForeignKey(GuardianInfo, on_delete=models.CASCADE, null=True, blank=True,)
    # emergency_contact_info = models.ForeignKey(EmergencyContactDetails, on_delete=models.CASCADE, null=True, blank=True,)
    # previous_academic_info = models.ForeignKey(PreviousAcademicInfo, on_delete=models.CASCADE, null=True, blank=True,)
    # previous_academic_certificate = models.ForeignKey(PreviousAcademicCertificate, on_delete=models.CASCADE, null=True, blank=True,)
    date = models.DateField(auto_now_add=True)
    is_delete = models.BooleanField(default=False)

    def __str__(self):
        return str(self.registration_no)

class EnrolledStudent(models.Model):
    # class_name = models.ForeignKey(ClassRegistration, on_delete=models.CASCADE)
    class_name = models.ForeignKey(ClassInfo, on_delete=models.CASCADE)
    student = models.OneToOneField(AcademicInfo, on_delete=models.CASCADE)
    roll = models.IntegerField()
    date = models.DateField(auto_now_add=True)

    class Meta:
        unique_together = ['class_name', 'roll']

    def __str__(self):
        return str(self.roll)




class ExcelUpload(models.Model):
    excell_sheet = models.FileField(null=True, blank=True)


class Cert(models.Model):


    pdf = models.FileField(upload_to='files', blank=True, null=True)

templates/student/class-wise-student-registration.html
{% extends 'base/base.html' %}
{% block content %}
  <div class="card">
      <div class="card-header">
          <i class="fa fa-align-justify"></i>Class List</div>
      <div class="card-body">
          <table class="table table-responsive-sm">
              <thead>
                  <tr>
                      <th>Id</th>
                      <th>Class Name</th>
                      <th>Section</th>
                      <th>Session</th>
                      <th>Shift</th>
                      <th>Department</th>
                      <th>Guide Teacher</th>
                      <th>Action</th>
                  </tr>
              </thead>
              <tbody>
                  {% for cls in register_class %}
                    <tr>
                        <td>{{ cls.id }}</td>
                        <td>{{ cls.class_name }}</td>
                        <td>{{ cls.section }}</td>
                        <td>{{ cls.session }}</td>
                        <td>{{ cls.shift }}</td>
                        <td>{{ cls.department }}</td>
                        <td>{{ cls.guide_teacher }}</td>
                        <td>
                          <a class="btn btn-success" href="{% url 'student-registration' cls.id %}">
                              <i class="fa fa-search-plus"></i>
                          </a>
                          <a class="btn btn-info" href="{% url 'student-list' cls.id %}">
                              <i class="fa fa-eye"></i>
                          </a>
                        </td>
                    </tr>
                  {% endfor %}
              </tbody>
          </table>
      </div>
  </div>
{% endblock %}

templates/student/enrolled.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <h2>Student Enrolled Here!</h2>
    <form action="" method="GET">
        {{ forms }}
        <input type="submit" value="Go">
    </form>
    {% if student %}
    <div class="animated fadeIn">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-edit"></i> Student Tables
            </div>
            <div class="card-body">
                <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-striped table-bordered datatable dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info" style="border-collapse: collapse !important">
                                <thead>
                                    <tr role="row">
                                        <th>Id</th>
                                        <th>Name</th>
                                        <th>Reg No</th>
                                        <th>Class</th>
                                        <th>Status</th>
                                        <th>Date</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for student in student %}
                                      <tr role="row" class="odd">
                                          <td>{{ forloop.counter }}</td>
                                          <td>{{ student.personal_info.name }}</td>
                                          <td>{{ student.registration_no }}</td>
                                          <td>{{ student.class_info }}</td>
                                          <td>{{ student.status }}</td>
                                          <td>{{ student.date }}</td>
                                          <td>
                                              <a class="btn btn-success" href="{% url 'student-profile' student.registration_no %}">
                                                  <i class="fa fa-search-plus"></i>
                                              </a>
                                              <a class="btn btn-success" href="{% url 'enrolled' student.registration_no %}">Enroll</a>
                                          </td>
                                      </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="{% static 'src/js/enroll.js' %}"></script>
    {% endif %}
{% endblock %}

templates/student/stud2.html
<div class="card">
  <!-- <div class="card-header">
    <i class="fa fa-edit"></i> Student Tables
    
  </div> -->
  <div class="card-body">
    <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
      <div class="row">
        <form id="a_form" role="form" method="POST" enctype="multipart/form-data" action="{% url 'student-list2' %}">
            {% csrf_token %}
          {{ form.as_p }}

          <button id="upload_form" type="submit" class="btn btn-primary" >Upload</button>
        </form>
        </div>
    </div>
</div>

templates/student/student-info-edit.html
<style type="text/css">
     label {
        width: 100%;
      }



  </style>

  <style type="text/css">
     .lab {
        width: 100%;
      }

      .wrap-input100 {
        color: red;
      }




      #is_delete{
        width: 50px;
      }



  </style>




  {% if academic_info_form.errors %}
    {% for field in academic_info_form %}
        {% for error in field.errors %}
            <div>
                <strong style="color:red;">{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in academic_info_form.non_field_errors %}
        <div>
            <strong style="color:red;">{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}



{% if user_creation_form.errors %}
    {% for field in user_creation_form %}
        {% for error in field.errors %}
            <div>
                <strong style="color:red;">{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in user_creation_form.non_field_errors %}
        <div>
            <strong style="color:red;">{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}



{% if personal_info_form.errors %}
    {% for field in personal_info_form %}
        {% for error in field.errors %}
            <div>
                <strong style="color:red;">{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in personal_info_form.non_field_errors %}
        <div>
            <strong style="color:red;">{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}



        <div class="card">
          <div class="card-header">Edit Information</div>
          <div class="card-body">
            {% csrf_token %}


            <label class="lab" for="id_first_name">Class:</label>
              {{ personal_info_form.class_of_student }}<br>



              <!-- <label for="id_username">Registration no</label>
              {{ user_creation_form.username }}<br>
              {% if user_creation_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ user_creation_form.username.errors }}</div>
                  {% endif %} -->

              <label for="id_first_name">First name:</label>
              {{ personal_info_form.first_name }}<br>
              {% if personal_info_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ personal_info_form.first_name.errors }}</div>
                  {% endif %}

              <label for="id_last_name">Last name:</label>
              {{ personal_info_form.last_name }}<br>
              {% if personal_info_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ personal_info_form.last_name.errors }}</div>
                  {% endif %}

              <!-- <label for="id_email">Email:</label>
              {{ user_creation_form.email }}<br>
              {% if user_creation_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ user_creation_form.email.errors }}</div>
                  {% endif %}
              {% if personal_info_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ personal_info_form.email.errors }}</div>
                  {% endif %}

              <label for="id_password1">Password:</label>
              {{ user_creation_form.password1 }}<br>
              {% if user_creation_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ user_creation_form.password1.errors }}</div>
                  {% endif %}

              <label for="id_password2">Password confirmation:</label>
              {{ user_creation_form.password2 }}<br>
              {% if user_creation_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ user_creation_form.password2.errors }}</div>
                  {% endif %} -->


              <label for="id_photo">Photo:</label>
              {{ personal_info_form.photo }}<br>
              {% if personal_info_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ personal_info_form.photo.errors }}</div>
                  {% endif %}

              <label for="id_date_of_birth">Date of birth:</label>
              {{ personal_info_form.date_of_birth }}<br>
              {% if personal_info_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ personal_info_form.date_of_birth.errors }}</div>
                  {% endif %}

              <label for="id_gender">Gender:</label>
              {{ personal_info_form.gender }}<br>
              {% if personal_info_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ personal_info_form.gender.errors }}</div>
                  {% endif %}


              <label for="id_phone_no">Phone no:</label>
              {{ personal_info_form.phone_no }}<br>
              {% if personal_info_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ personal_info_form.phone_no.errors }}</div>
                  {% endif %}

              <label for="id_religion">Religion:</label>
              {{ personal_info_form.religion }}<br>
              {% if personal_info_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ personal_info_form.religion.errors }}</div>
                  {% endif %}

              <label for="id_nationality">Nationality:</label>
              {{ personal_info_form.nationality }}<br>
              {% if personal_info_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ personal_info_form.nationality.errors }}</div>
                  {% endif %}


                  <div class="card">
          <div class="card-header">Delete Student</div>
          <div class="card-body">
                  <label id="is_delete" for="id_is_delete">Delete:</label>
              {{ academic_info_form.is_delete }}<br>
              {% if academic_info_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ academic_info_form.is_delete.errors }}</div>
                  {% endif %}

                </div>
              </div>
            </div>



          </div>
        </div>




<script type="text/javascript">

      var class_of_student = document.querySelector('#id_class_of_student');
      var first_name = document.querySelector('#id_first_name');
      var last_name = document.querySelector('#id_last_name');
      var photo = document.querySelector('#id_photo');
      var date_of_birth = document.querySelector('#id_date_of_birth');
      var gender = document.querySelector('#id_gender');
      var phone_no = document.querySelector('#id_phone_no');
      var religion = document.querySelector('#id_religion');
      var nationality = document.querySelector('#id_nationality');



      class_of_student.setAttribute('class', 'form-control lab');
      first_name.setAttribute('class', 'form-control lab');
      last_name.setAttribute('class', 'form-control lab');

      photo.setAttribute('class', 'form-control lab');
      date_of_birth.setAttribute('class', 'form-control lab');

      date_of_birth.setAttribute('type', 'date');
      gender.setAttribute('class', 'form-control lab');

      phone_no.setAttribute('class', 'form-control lab');
      phone_no.setAttribute('type', 'number');
      religion.setAttribute('class', 'form-control lab');

      nationality.setAttribute('class', 'form-control lab');


      class_of_student.required = true;
      first_name.required = true;
      last_name.required = true;

</script>

templates/student/student-list.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<style type="text/css">
  #check {
    visibility: hidden;
  }
</style>
    <div class="animated fadeIn">
        <div class="card">
            <div class="card-header">
                <h5>Select class to retrieve list</h5>
            </div>
            <div class="card-body">
                <form id="select_class" action="" method="POST">
                  {% csrf_token %}
                  <label>Select class:
                    {{ forms.class_info }}
                  </label>
                </form>
                <input id="check" type="text" value="{{ username }}">

            </div>
        </div>
    </div>
    <!-- Large modal -->


<div class="modal fade bd-example-modal-lg" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Edit Student Information</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <form id="a_form3" role="form" enctype="multipart/form-data" method="POST" action="">
            {% csrf_token %}
            <div id="edit-teacher">
            </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button id="upload_form3" type="submit" class="btn btn-primary" form="a_form3">Save changes</button>
      </div>
    </div>
  </div>
</div>






<div class="modal fade bd-example-modal-lg" id="exampleModalScrollable1" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Change Student Password</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <form id="a_form4" role="form" enctype="multipart/form-data" method="POST" action="">
            {% csrf_token %}
            <div id="edit-password">
            </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button id="upload_form4" type="submit" class="btn btn-primary" form="a_form4">Save changes</button>
      </div>
    </div>
  </div>
</div>




                                          <!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalCenterTitle">Upload Result</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="show_message">{{ message }}</div>
        <form id="a_form" role="form" method="POST" enctype="multipart/form-data" action="">
            {% csrf_token %}
          {{ forms1.pdf }}

        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button id="upload_form" type="submit" class="btn btn-primary" form="a_form">Upload</button>
      </div>

    </div>
  </div>
</div>
<!-- Modal end -->
    <div id="student_list" class="animated fadeIn">



    </div>
{% endblock %}










{% block java %}
  <script>

     var class_info = document.querySelector('#id_class_info');

      class_info.id = "class_class";



$(document).ready(function(){
  $('#select_class').on('change', function(e){
    e.preventDefault();
    var class_info = $("#class_class option:selected").text();
    console.log(class_info)

    saveans1(class_info);
  });

  function saveans1(class_info){
      $.ajax({
          type: 'POST',
          url: "{% url 'student-list' %}",
          headers: {'X-CSRFToken': csrftoken},
          data : {
                'class_info': class_info
            },
            beforeSend: function () { // Before we send the request, remove the .hidden class from the spinner and default to inline-block.
                $("#overlay").fadeIn(300);　
            },
          success: function(data){
              //console.log(data.form)
              var std_lst = $('#student_list');
              std_lst.html(data.form);
          },
          complete: function () { // Set our complete callback, adding the .hidden class and hiding the spinner.
                 $("#overlay").fadeOut(300);
            }

      });
      return false;
  }

  function getCookie(name){
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
              const cookie = cookies[i].trim();
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
  }
  const csrftoken = getCookie('csrftoken');



});









</script>


<script type="text/javascript">
                  $(document).ready(function(){

                    console.log("check1")

                    $(document).ready(function(){
                      var check = $('#check').val();
                      console.log("check")
                      console.log(check)
                      if (check) {
                        var class_info = check;
                        console.log(class_info)

                        saveans5(class_info);

                      }

                    });



                    function saveans5(class_info){
                        $.ajax({
                            type: 'POST',
                            url: "{% url 'student-list' %}",
                            headers: {'X-CSRFToken': csrftoken},
                            data : {
                                  'class_info': class_info
                              },
                             beforeSend: function () { // Before we send the request, remove the .hidden class from the spinner and default to inline-block.
                                    $("#overlay").fadeIn(300);　
                                },
                            success: function(data){
                                //console.log(data.form)
                                var std_lst = $('#student_list');
                                std_lst.html(data.form);
                            },

                            complete: function () { // Set our complete callback, adding the .hidden class and hiding the spinner.
                                 $("#overlay").fadeOut(300);
                            }
                        });
                        return false;
                    }

                    function getCookie(name){
                        let cookieValue = null;
                        if (document.cookie && document.cookie !== '') {
                            const cookies = document.cookie.split(';');
                            for (let i = 0; i < cookies.length; i++) {
                                const cookie = cookies[i].trim();
                                // Does this cookie string begin with the name we want?
                                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                    break;
                                }
                            }
                        }
                        return cookieValue;
                    }
                    const csrftoken = getCookie('csrftoken');

                  });
                </script>




    {% endblock %}

templates/student/upload-result.html
<span class="animated fadeIn" style="color: red">{{ message }}</span>
<br>