result/urls.py
from django.urls import path, re_path

from .views import *


app_name = 'result'


urlpatterns = [
    path('add-subject', add_subject, name='add-subject'),
    path('subject-list', subject_list, name='subject-list'),
    path('mark-entry', mark_entry, name='mark-entry'),
    #path('mark-entry-mid-term', mark_entry_mid_term, name='mark-entry-mid-term'),
    path('result-preview', pin_check, name='result-preview'),
    #path('result-preview-mid-term', pin_check_mid_term, name='result-preview-mid-term'),
    re_path(r'mid-term-result/(?P<reg_no>[\w/]+)/$', student_mid_term_result, name="student-mid-term-result"),
    re_path(r'print/(?P<level>[\w-]+)/(?P<term>[\w\s\w]+)/(?P<year>[\w/]+)/$', print_write_pdf_view, name="print"),
    re_path(r'download/(?P<level>[\w-]+)/(?P<term>[\w\s\w]+)/(?P<year>[\w/]+)/$', download_write_pdf_view, name="download"),
    #path('print/<level>/<term>/<year>', print_write_pdf_view, name='print'),
    #path('download/<level>/<term>/<year>', download_write_pdf_view, name='download'),
    path('mark-table/<subject>', mark_table, name='mark-table'),

]

schoolmanagement/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .views import home_page, preview
import teacher.views as views
import student.views as student_views
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

import django.contrib.auth.views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('preview/', preview, name='preview'),
    path('', include('administration.urls')),
    #re_path(r'classroom-delete/(?P<class_name>[\w/]+)/$', views.create_class_delete, name="classroom-delete"),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('academic/', include('academic.urls')),
    path('employee/', include('employee.urls')),
    path('result/', include('result.urls')),
    path('address/', include('address.urls')),
    path('account/', include('account.urls')),
    path('attendance/', include('attendance.urls')),
    re_path(r'password_change/(?P<username>[\w/]+)/$', student_views.change_password, name="password_change"),
    #path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teacher/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('registration', views.teacher_registration, name='teacher-registration'),
    path('list', views.teacher_list, name='teacher-list'),
    path('teacher-upload/', views.excell_teacher_registration, name='excell_teacher_registration'),
    path('list-search', views.teacher_list_search, name='teacher-list-search'),
    path('teachers-excel-format', views.export_teachers_registration_xls, name='export_teachers_registration_xls'),
    path('create-classroom/', views.create_class, name='create-classroom'),
    path('create-classroom-edit/', views.create_class_edit, name='create-classroom-edit'),
    re_path(r'password_change1/(?P<username>[\w/]+)/$', views.change_password, name="password_change1"),
    re_path(r'teacher-assign-assign/(?P<username>[\w/]+)/$', views.teacher_assign1, name="teacher-assign-assign"),
    re_path(r'teacher-assign/(?P<username>[\w/]+)/$', views.teacher_assign, name="teacher-assign"),
    re_path(r'teacher-edit-edit/(?P<username>[\w/]+)/$', views.teacher_edit, name="teacher-edit-edit"),
    re_path(r'make-admin/(?P<username>[\w/]+)/$', views.make_admin, name="make-admin"),
    re_path(r'remove-admin/(?P<username>[\w/]+)/$', views.remove_admin, name="remove-admin"),
    re_path(r'admin-edit/(?P<username>[\w/]+)/$', views.admin_edit, name="admin-edit"),
    path('deleted-teachers', views.deleted_teachers, name='deleted-teachers'),
    re_path(r'deleted-teachers/(?P<username>[\w/_]+)/$', views.deleted_teachers, name="deleted-teachers-re"),
    re_path(r'restore-teachers-re/(?P<username>[\w/_]+)/$', views.restore_teachers_re, name="restore-teachers-re"),
    #re_path(r'teacher-edit-assign/(?P<username>[\w/]+)/$', views.teacher_edit_assign, name="teacher-edit-assign"),
    re_path(r'teacher-assign-delete/(?P<username>[\w/]+)/$', views.teacher_assign_delete, name="teacher-assign-delete"),
    #re_path(r'create-classroom-edit/(?P<class_name>[\w/]+)/', views.create_class_edit, name="create-classroom-edit"),
    path('profile/<teacher_id>', views.teacher_profile, name='teacher-profile'),
    re_path(r'deleted-teachers/(?P<username>[\w/_]+)/$', views.deleted_teachers, name="deleted-teachers-re"),
    #path('delete/<teacher_id>', views.teacher_delete, name='teacher-delete'),
    re_path(r'teacher-delete/(?P<username>[\w/_]+)/$', views.teacher_delete, name="teacher-delete"),
    path('edit/<teacher_id>', views.teacher_edit, name='teacher-edit'),
    path('load-upazilla', views.load_upazilla, name='load-upazilla'),
    re_path(r'classroom-delete/(?P<class_name>[\w]+)/$', views.create_class_delete, name="classroom-delete"),
]

address/models.py
from django.db import models

class District(models.Model):
    name = models.CharField(max_length=45, unique=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class Upazilla(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=45, unique=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class Union(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    upazilla = models.ForeignKey(Upazilla, on_delete=models.CASCADE)
    name = models.CharField(max_length=45, unique=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

teacher/models.py
from django.db import models
from django.contrib.auth.models import User
from academic.models import Department
from administration.models import *
from address.models import District, Upazilla, Union
from academic.models import ClassInfo


from django.template.loader import render_to_string
from django.utils.safestring import mark_safe
from django.db.models.fields import BLANK_CHOICE_DASH
from django.core.validators import FileExtensionValidator
import uuid
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify



class EducationInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="teacher_education", null=True, blank=True,)
    name_of_degree = models.CharField(max_length=100, null=True, blank=True,)
    institute = models.CharField(max_length=255, null=True, blank=True,)
    passing_year_date = models.DateField(null=True, blank=True,)
    grade = models.FloatField(max_length=45, null=True, blank=True,)
    certificate = models.FileField(upload_to='documents/', null=True, blank=True,)
    upload_cv = models.FileField(upload_to='documents/', null=True, blank=True,)


    def __str__(self):
        return self.user.username




class PersonalInfo(models.Model):
    #name = models.CharField(max_length=45)
    first_name = models.CharField(max_length=45, null=True, blank=True,)
    last_name = models.CharField(max_length=45, null=True, blank=True,)
    pass_word = models.CharField(max_length=45, null=True, blank=True,)
    employee_code = models.CharField(max_length=45, null=True, blank=True, unique=True)
    user = models.ForeignKey(User, default='', on_delete=models.CASCADE, related_name="user_teacher",)
    photo = models.ImageField(null=True, blank=True,)
    classes_assigned = models.CharField(max_length=1500, null=True, blank=True,)
    date_of_birth = models.DateField(blank=True, null=True,)
    date_employed= models.DateField(blank=True, null=True,)
    education = models.ForeignKey(EducationInfo, on_delete=models.CASCADE, blank=True, null=True)
    nationality_choice = (
        ('Ghana', 'Ghana'),
        ('Nigeria', 'Nigeria')
    )
    nationality = models.CharField(max_length=45, blank=True, null=True, choices=nationality_choice)
    religion_choice = (
        ('Islam', 'Islam'),
        ('Christianity', 'Christianity')
    )
    religion = models.CharField(max_length=45, blank=True, null=True, choices=religion_choice)
    gender_choice = (
        ('male', 'Male'),
        ('female', 'Female')
    )
    gender = models.CharField(choices=gender_choice, blank=True, null=True, max_length=10)
    driving_license_passport = models.IntegerField(unique=True, blank=True, null=True,)
    phone_no = models.CharField(max_length=11, unique=True, blank=True, null=True,)
    email = models.CharField(max_length=255, blank=True, null=True,)
    marital_status_choice = (
        ('married', 'Married'),
        ('widowed', 'Widowed'),
        ('separated', 'Separated'),
        ('divorced', 'Divorced'),
        ('single', 'Single')
    )
    marital_status = models.CharField(choices=marital_status_choice, max_length=10,blank=True, null=True)
    address = models.CharField(max_length=2000, blank=True, null=True)
    is_delete = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class ClassAssignedToTeacher(models.Model):
    name = models.CharField(max_length=45, null=True, blank=True,)
    personal_info = models.ForeignKey(PersonalInfo, on_delete=models.CASCADE, null=True, blank=True, related_name="teacher_persona")
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name='classes_assigned_teacher')

    class Meta:
        verbose_name = 'Class Assigned To Teacher'
        verbose_name_plural = 'Class Assigned To Teacher'

    def __str__(self):
        return self.name


class ExcelUpload(models.Model):
    excell_sheet = models.FileField(null=True, blank=True)

templates/teacher/admin-info-edit.html
<style type="text/css">
     label {
        width: 100%;
      }



  </style>



<style type="text/css">
     .lab {
        width: 100%;
      }

      #photoss {
        width: 20%;
      }


      #is_delete{
        width: 50px;
      }

      .wrap-input100 {
        color: red;
      }



  </style>



  {% if education_form.errors %}
    {% for field in education_form %}
        {% for error in field.errors %}
            <div>
                <strong style="color:red;">{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in education_form.non_field_errors %}
        <div>
            <strong style="color:red;">{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}



{% if user_creation_form.errors %}
    {% for field in user_creation_form %}
        {% for error in field.errors %}
            <div>
                <strong style="color:red;">{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in user_creation_form.non_field_errors %}
        <div>
            <strong style="color:red;">{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}



{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div>
                <strong style="color:red;">{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div>
            <strong style="color:red;">{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

        <div class="card">
          <div class="card-header">Personal Information</div>
          <div class="card-body">
            {% csrf_token %}


              <label for="id_first_name">First name:</label>
              {{ form.first_name }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.first_name.errors }}</div>
                  {% endif %}

              <label for="id_last_name">Last name:</label>
              {{ form.last_name }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.last_name.errors }}</div>
                  {% endif %}



              <label for="id_photo">Photo:</label>
              {{ form.photo }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.photo.errors }}</div>
                  {% endif %}

              <label for="id_gender">Gender:</label>
              {{ form.gender }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.gender.errors }}</div>
                  {% endif %}

              <label for="id_gender">Date of birth:</label>
              {{ form.date_of_birth }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.date_of_birth.errors }}</div>
                  {% endif %}

             <label for="id_gender">Marital status:</label>
              {{ form.marital_status }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.marital_status.errors }}</div>
                  {% endif %}

              <label for="id_phone_no">Phone no:</label>
              {{ form.phone_no }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.phone_no.errors }}</div>
                  {% endif %}

              <label for="id_email">Address:</label>
              {{ form.address }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.address.errors }}</div>
                  {% endif %}

              <label for="id_religion">Religion:</label>
              {{ form.religion }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.religion.errors }}</div>
                  {% endif %}

              <label for="id_nationality">Nationality:</label>
              {{ form.nationality }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.nationality.errors }}</div>
                  {% endif %}


          </div>
        </div>


        <div class="card">
          <div class="card-header">Delete Admin</div>
          <div class="card-body">
                  <label id="is_delete" for="id_is_delete">Delete:</label>
              {{ form.is_delete }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.is_delete.errors }}</div>
                  {% endif %}

                </div>
              </div>
            </div>

templates/teacher/class-assign.html
{{ forms2.class_info }}

<script type="text/javascript">
	
	var class_info = document.querySelector('#id_class_info');
	class_info.setAttribute('name', 'class_info');
	
	class_info.multiple = true;

	var text_area = document.querySelectorAll(".select2-search--inline")[0];
	text_area.setAttribute('style', 'display:none');


    $(document).ready(function() {
	    $('#id_class_info').select2({
	    	dropdownParent: $("#exampleModalCenter"),
	    	theme: "classic"
	    });
	});

</script>

templates/teacher/create-class.html
{% extends 'base/base.html' %}
{% load static %}




{% block content %}
<style type="text/css">
     label {
        display: flex;
      }

      @media screen and (min-width: 536px) {
      label { 
        width: 10%;
        display: inline-block;
      }
    }

      

  </style>



  {% if forms1.errors %}
    {% for field in forms1 %}
        {% for error in field.errors %}
            <div>
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in forms1.non_field_errors %}
        <div>
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}






  


  <div class="card">
    <div class="card-header">Class Register Form</div>
    <div class="card-body">
      <form class="" action="" method="post" enctype="multipart/form-data" id="StudentRegistrationForm" data-upazilla-url="{% url 'load-upazilla' %}">
        <div class="academic_info">

            <div class="card-body">
              {% csrf_token %}



              {{ forms1.as_p }}

             
            </div>
          <button id="create_class" type="submit" class="btn btn-primary pull-left">Save</button>
        </div>

            <!-- {% if teacher_personal_info|length  > 0 %}
            <div class="card-body">
              {% csrf_token %}



              {{ forms1.as_p }}

             
            </div>

            </div>
          <button id="academic_info_btn" type="button" class="btn btn-primary pull-right">Next</button>
        </div>

            {% else %}
            <div class="card-body">
              <h3>No Assigned Class To Add Student</h3>
          </div>
          </div>
         
        </div>
            {% endif %} -->

        

        

      </form>
      
    </div>
  </div>
{% endblock %}



{% block java %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script src="{% static 'src/js/registration.js' %}"></script>
      <script src="{% static 'src/js/address.js' %}"></script>
  <script>
console.log("whyyyyyyyyyyyyy")

 $(document).ready(function() {
    $('.class_name').click(function(e){
      e.preventDefault();
        var class_name1 = $(this).attr("data-class");
        console.log(class_name1)

        var action = $('#a_form').attr('action', 'http://127.0.0.1:8000/teacher/create-class/');


        $.ajax({
            url: 'http://127.0.0.1:8000/teacher/create-classroom/',
            headers: {'X-CSRFToken': csrftoken},
            type: "POST",
            data: {
                "class_name": class_name1
            }
            success: function (data) {
              $('#edit-form').html(data.form);
            }
        });
        return false;



        function getCookie(name){
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');




    });

});


</script>
{% endblock %}

templates/teacher/edit-class.html
{{ forms2.name }}
<input id='edit_class_name' style='display: none;' type="text" name="prev_name" value="{{ class_name }}">


<script type="text/javascript">


	$('#id_name').blur(function(e){
    e.preventDefault();
    var val = $(this).val();
    var final =removeSpaces(val);
    $(this).val(final);


    function removeSpaces(string) {
     return string.split(' ').join('');
    }
});

</script>

templates/teacher/teacher-edit.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
  <div class="card">
    <div class="card-header">Teacher Registration Form</div>
    <div class="card-body">
      <form action="" method="post" enctype="multipart/form-data" id="TeacherRegistrationForm" data-upazilla-url={% url 'load-upazilla' %}>

        <div class="card">
          <div class="card-header">Personal Information</div>
          <div class="card-body">
            {% csrf_token %}
            {{ form.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Address Information</div>
          <div class="card-body">
            {% csrf_token %}
            {{ address_form.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Education Information</div>
          <div class="card-body">
            {% csrf_token %}
            {{ education_form.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Training Information</div>
          <div class="card-body">
            {% csrf_token %}
            {{ training_form.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Job Information</div>
          <div class="card-body">
            {% csrf_token %}
            {{ job_form.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Experience Information</div>
          <div class="card-body">
            {% csrf_token %}
            {{ experience_form.as_p }}
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script>
        $("#id_district").change(function () {
          var url = $("#TeacherRegistrationForm").attr("data-upazilla-url");
          var districtId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'district': districtId
            },
            success: function (data) {
              $("#id_upazilla").html(data);
            }
          });

        });
        $("#id_upazilla").change(function () {
          var url = $("#TeacherRegistrationForm").attr("data-upazilla-url");
          var upazillaId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'upazilla': upazillaId
            },
            success: function (data) {
              $("#id_union").html(data);
            }
          });

        });
      </script>
    </div>
  </div>
{% endblock %}

templates/teacher/teacher-info-edit.html
<style type="text/css">
     label {
        width: 100%;
      }



  </style>



<style type="text/css">
     .lab {
        width: 100%;
      }

      #photoss {
        width: 20%;
      }


      #is_delete{
        width: 50px;
      }

      .wrap-input100 {
        color: red;
      }



  </style>



  {% if education_form.errors %}
    {% for field in education_form %}
        {% for error in field.errors %}
            <div>
                <strong style="color:red;">{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in education_form.non_field_errors %}
        <div>
            <strong style="color:red;">{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}



{% if user_creation_form.errors %}
    {% for field in user_creation_form %}
        {% for error in field.errors %}
            <div>
                <strong style="color:red;">{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in user_creation_form.non_field_errors %}
        <div>
            <strong style="color:red;">{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}



{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div>
                <strong style="color:red;">{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div>
            <strong style="color:red;">{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

        <div class="card">
          <div class="card-header">Personal Information</div>
          <div class="card-body">
            {% csrf_token %}


              <label for="id_first_name">First name:</label>
              {{ form.first_name }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.first_name.errors }}</div>
                  {% endif %}

              <label for="id_last_name">Last name:</label>
              {{ form.last_name }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.last_name.errors }}</div>
                  {% endif %}



              <label for="id_photo">Photo:</label>
              {{ form.photo }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.photo.errors }}</div>
                  {% endif %}

              <label for="id_gender">Gender:</label>
              {{ form.gender }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.gender.errors }}</div>
                  {% endif %}

              <label for="id_gender">Date of birth:</label>
              {{ form.date_of_birth }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.date_of_birth.errors }}</div>
                  {% endif %}

             <label for="id_gender">Marital status:</label>
              {{ form.marital_status }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.marital_status.errors }}</div>
                  {% endif %}

              <label for="id_phone_no">Phone no:</label>
              {{ form.phone_no }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.phone_no.errors }}</div>
                  {% endif %}

              <label for="id_email">Address:</label>
              {{ form.address }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.address.errors }}</div>
                  {% endif %}

              <label for="id_religion">Religion:</label>
              {{ form.religion }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.religion.errors }}</div>
                  {% endif %}

              <label for="id_nationality">Nationality:</label>
              {{ form.nationality }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.nationality.errors }}</div>
                  {% endif %}


          </div>
        </div>


        <div class="card">
          <div class="card-header">Education Information</div>
          <div class="card-body">
            {% csrf_token %}



            <label for="id_nationality">Name of degree:</label>
              {{ education_form.name_of_degree }}<br>
              {% if education_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ education_form.name_of_degree.errors }}</div>
                  {% endif %}


                  <label for="id_nationality">Institute:</label>
              {{ education_form.institute }}<br>
              {% if education_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ education_form.institute.errors }}</div>
                  {% endif %}


                  <label for="id_nationality">Passing year date:</label>
              {{ education_form.passing_year_date }}<br>

              {% if education_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ education_form.passing_year_date.errors }}</div>
                  {% endif %}


                  <label for="id_nationality">Grade:</label>
              {{ education_form.grade }}<br>
              {% if education_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ education_form.grade.errors }}</div>
                  {% endif %}


                  <label for="id_nationality">Certificate:</label>
              {{ education_form.certificate }}<br>
              {% if education_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ education_form.certificate.errors }}</div>
                  {% endif %}


              <label for="id_nationality">Upload CV:</label>
              {{ education_form.upload_cv }}<br>
              {% if education_form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ education_form.upload_cv.errors }}</div>
                  {% endif %}
          </div>
        </div>


        <div class="card">
          <div class="card-header">Delete Teacher</div>
          <div class="card-body">
                  <label id="is_delete" for="id_is_delete">Delete:</label>
              {{ form.is_delete }}<br>
              {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.is_delete.errors }}</div>
                  {% endif %}

                </div>
              </div>
            </div>



<script type="text/javascript">
  var date_of_birth = document.querySelector('#id_date_of_birth');
   var passing_year_date = document.querySelector('#id_passing_year_date');



      date_of_birth.setAttribute('type', 'date');


      passing_year_date.setAttribute('type', 'date');
</script>