result/urls.py
from django.urls import path, re_path

from .views import *


app_name = 'result'


urlpatterns = [
    path('add-subject', add_subject, name='add-subject'),
    path('subject-list', subject_list, name='subject-list'),
    path('mark-entry', mark_entry, name='mark-entry'),
    #path('mark-entry-mid-term', mark_entry_mid_term, name='mark-entry-mid-term'),
    path('result-preview', pin_check, name='result-preview'),
    #path('result-preview-mid-term', pin_check_mid_term, name='result-preview-mid-term'),
    re_path(r'mid-term-result/(?P<reg_no>[\w/]+)/$', student_mid_term_result, name="student-mid-term-result"),
    re_path(r'print/(?P<level>[\w-]+)/(?P<term>[\w\s\w]+)/(?P<year>[\w/]+)/$', print_write_pdf_view, name="print"),
    re_path(r'download/(?P<level>[\w-]+)/(?P<term>[\w\s\w]+)/(?P<year>[\w/]+)/$', download_write_pdf_view, name="download"),
    #path('print/<level>/<term>/<year>', print_write_pdf_view, name='print'),
    #path('download/<level>/<term>/<year>', download_write_pdf_view, name='download'),
    path('mark-table/<subject>', mark_table, name='mark-table'),

]

schoolmanagement/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .views import home_page, preview
import teacher.views as views
import student.views as student_views
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

import django.contrib.auth.views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('preview/', preview, name='preview'),
    path('', include('administration.urls')),
    #re_path(r'classroom-delete/(?P<class_name>[\w/]+)/$', views.create_class_delete, name="classroom-delete"),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('academic/', include('academic.urls')),
    path('employee/', include('employee.urls')),
    path('result/', include('result.urls')),
    path('address/', include('address.urls')),
    path('account/', include('account.urls')),
    path('attendance/', include('attendance.urls')),
    re_path(r'password_change/(?P<username>[\w/]+)/$', student_views.change_password, name="password_change"),
    #path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

result/models.py
from django.db import models

from academic.models import ClassRegistration

# Create your models here.

class SubjectRegistration(models.Model):
    select_class = models.ForeignKey(ClassRegistration, on_delete=models.CASCADE, null=True)
    subject_name = models.CharField(max_length=45)
    subject_code = models.IntegerField(unique=True)
    marks = models.IntegerField()
    pass_mark = models.IntegerField()
    add_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.subject_name

result/forms.py
from django import forms
from .models import SubjectRegistration, ClassRegistration

from django.contrib.auth.models import User

from administration.models import *




# class UserLoginForm(forms.Form):
#     username = forms.CharField(label="", widget= forms.TextInput(attrs = {'placeholder':'Username'}))
#     password = forms.CharField(label="", widget=forms.PasswordInput(attrs = {'placeholder':'Pin'}))


class PinCheckForm(forms.ModelForm):
    pin = forms.CharField(label="", widget=forms.PasswordInput())

    class Meta:
        model = Administration
        fields = ('term',)



class PinCheckForm2(forms.ModelForm):

    class Meta:
        model = Administration
        fields = ('term',)





class NumberOfPin(forms.ModelForm):
    class Meta:
        model = Number
        fields = (
            'numbers',
            )




class YearForm(forms.Form):
    username = forms.CharField(label="", widget= forms.TextInput(attrs = {'placeholder':'Username'}))
    password = forms.CharField(label="", widget=forms.PasswordInput(attrs = {'placeholder':'Pin'}))


class StudentsLevelForm(forms.ModelForm):
    class Meta:
        model = StudentsInClass
        fields = ('level',)





class ClassLevelForm(forms.ModelForm):
    class Meta:
        model = ClassLevel
        fields = ('class_level',)


class AdministrationForm(forms.ModelForm):
    class Meta:
        model = Administration
        fields = ('term',)


# class TermForm(forms.ModelForm):
#     class Meta:
#         model = Performance
#         fields = ('term',)


# class YearForm(forms.ModelForm):
#     class Meta:
#         model = Performance
#         fields = ('year',)

# class PerformanceForm(forms.ModelForm):
#     class Meta:
#         model = Performance
#         fields = ('year', 'pdf', 'user', 'clas', 'term',)


# class UpdateForm(forms.ModelForm):
#     class Meta:
#         model = Performance
#         fields = ('year', 'pdf', 'user', 'clas', 'term',)





class SubjectRegistrationForm(forms.ModelForm):
    class Meta:
        model = SubjectRegistration
        fields = '__all__'

        widgets = {
            'select_class': forms.Select(attrs={'class': 'form-control'}),
            'subject_name': forms.TextInput(attrs={'class': 'form-control'}),
            'subject_code': forms.NumberInput(attrs={'class': 'form-control'}),
            'marks': forms.NumberInput(attrs={'class': 'form-control'}),
            'pass_mark': forms.NumberInput(attrs={'class': 'form-control'}),
        }

class ClassSelectSubjectListForm(forms.Form):
    select_class = forms.ModelChoiceField(queryset=ClassRegistration.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))


class ClassSelectMarkEntryForm(forms.Form):
    select_class = forms.ModelChoiceField(queryset=ClassRegistration.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))



class ClassSelectMarkEntryForm2(forms.Form):
    select_class = forms.ModelChoiceField(queryset=ClassRegistration.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))

result/views.py
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from academic.models import ClassRegistration
from .forms import SubjectRegistrationForm, ClassSelectMarkEntryForm, ClassSelectSubjectListForm
from .models import SubjectRegistration
from student.models import AcademicInfo
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.conf import settings
from django.contrib import messages
from.forms import *
from.models import *
# from student.models import *
from teacher.models import *
from student.models import AcademicInfo, PersonalInfo
from administration.models import *
from academic.models import *
from django.contrib.auth.decorators import permission_required
#import xlwt
from django.contrib.auth.decorators import login_required




from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags

import datetime
from io import BytesIO
from reportlab.pdfgen import canvas

import time

import logging


logger = logging.getLogger(__name__)

def add_subject(request):
    form  = SubjectRegistrationForm()
    if request.method == 'POST':
        form = SubjectRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('subject-list')
    context = {'form': form}
    return render(request, 'result/add-subject.html', context)

def subject_list(request):
    form = ClassSelectSubjectListForm(request.GET or None)
    select_class = request.GET.get('select_class', None)
    if select_class:
        cls = ClassRegistration.objects.get(id=select_class)
        subjects = SubjectRegistration.objects.filter(select_class=cls)
        context = {'form': form, 'subjects': subjects}
        return render(request, 'result/subject-list.html', context)

    context = {'form': form}
    return render(request, 'result/subject-list.html', context)

def mark_entry1(request):
    form = ClassSelectMarkEntryForm(request.GET or None)
    select_class = request.GET.get('select_class', None)
    if select_class:
        cls = ClassRegistration.objects.get(id=select_class)
        student = AcademicInfo.objects.filter(class_info=cls)
        context = {'form': form, 'student': student}
        return render(request, 'result/mark-entry.html', context)
    context = {'form': form}
    return render(request, 'result/mark-entry.html', context)










@login_required(login_url='administration:login')
def mark_entry(request):
    # global response

    group_students = []
    try:
        result = Result.objects.filter(user=request.user)[0]
    except:
        result = None
    if result:
        year = result.year
        level = result.clas
    else:
        year = None
        level = None
    group_student = User.objects.filter(groups__name='Students')
    print(group_student)
    group_admin = Group.objects.get(name="Admin")
    for i in group_student:
        group_students.append(i.username)

    form = PinCheckForm()
    context = {
        'result': result,
        'form': form,
        'group_students':group_students,
        'year': year,
        'level': level,
    }
    return render(request, 'result/mark-entry.html', context)



def download_write_pdf_view(request, level, term, year):
    personal_info = PersonalInfo.objects.get(user=request.user)
    print(personal_info)
    level1 = ClassInfo.objects.get(name=level)
    term1 = Term.objects.get(term=term)
    year1 = Year.objects.get(time=year)
    result = Result.objects.get(user=request.user, clas=level1, term=term1, year=year1)
    print(request.user.last_name)
    print(request.user.first_name)
    mypdf = result.pdf
    response = HttpResponse(mypdf, content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename={personal_info.last_name.capitalize()}' + f'_{personal_info.first_name.capitalize()}_' + f'{result.term}_result' + '.pdf'
    return response


def print_write_pdf_view(request, level, term, year):
    personal_info = PersonalInfo.objects.get(user=request.user)
    level1 = ClassInfo.objects.get(name=level)
    term1 = Term.objects.get(term=term)
    year1 = Year.objects.get(time=year)
    result = Result.objects.get(user=request.user, clas=level1, term=term1, year=year1)
    mypdf = result.pdf
    response = HttpResponse(mypdf, content_type='application/pdf')
    response['Content-Disposition'] = f'inline; filename={personal_info.last_name.capitalize()}' + f'__{personal_info.first_name.capitalize()}__' + f'__{result.term}_result' + '.pdf'
    return response

def pin_check(request):
    username = request.user.username
    group_students = []
    user = User.objects.get(username=username)
    #personal_info = AcademicInfo.objects.get(registration_no=username).class_info.name
    level = AcademicInfo.objects.get(registration_no=username).class_info.name
    group_student = User.objects.filter(groups__name='Students')
    for i in group_student:
        group_students.append(i.username)
    try:
        result = Result.objects.filter(user=user)[0]
    except:
        result = None

    form = PinCheckForm()



    current_term1 = CurrentTerm.objects.all()[0].name
    current_term = Term.objects.get(term=current_term1)

    current_session1 = CurrentSession.objects.all()[0].name
    current_session = Year.objects.get(time=current_session1)




    try:
        result = Result.objects.get(user=request.user, year=current_session, term=current_term)
    except:
        result = None



    #if request.is_ajax and request.method == "POST":
    if request.method == "POST":
        forms = PinCheckForm(request.POST)
        if forms.is_valid():
            if result != None:
                year = Year.objects.get(time=current_session1)
                term = forms.cleaned_data['term']
                pin = forms.cleaned_data['pin']
                try:
                    pin_available = PinCode.objects.get(reference=pin)
                except ObjectDoesNotExist:
                    pin_available = None
                if pin_available:
                    try:
                        expire = pin_available.expiry_date

                        #check if the days left is greater or equal to the post's duration
                        if expire <= datetime.datetime.now():

                            #if duration exceeded delete post
                            pin_available.delete()
                            messages.success(request, "Pin expired", extra_tags='error')
                            return HttpResponseRedirect(reverse('result:mark-entry'))
                        else:

                            check_count = PinCodeTime.objects.filter(reference=pin).count()
                            if check_count > 0:
                                check = PinCodeTime.objects.filter(reference=pin)
                                checking = PinCodeTime.objects.filter(reference=pin)[0]
                            else:
                                check = None
                    except ObjectDoesNotExist:
                        check = None
                    if check:
                        print(check)
                        if username == checking.user.username:
                            #fetch the requested result
                            level1 = ClassInfo.objects.get(name=level)
                            term1 = Term.objects.get(term=term)
                            year1 = Year.objects.get(time=year)
                            try:
                                result = Result.objects.get(user=request.user, clas=level1, term=term1, year=year1)
                            except:
                                result = None

                            if result != None:
                                if result == checking.result: #note thatperformance will not need [0] when it is a single object after using get on comment above
                                    if check_count <= 4:
                                        create_pin = PinCodeTime(reference=pin, user=request.user, result=result) #include Performcae object when creating PineCodeTime
                                        create_pin.save()
                                        context = {
                                            'result': result
                                        }
                                        #messages.success(request, "login successful.", extra_tags='success')
                                        # html = render_to_string('result/mark-entry1.html', context, request=request)
                                        # return JsonResponse({'form': html})
                                        return render(request, 'result/mark-entry1.html', context)
                                    else:
                                        pin_available.delete()
                                        check = PinCodeTime.objects.filter(reference=pin)
                                        for i in check:
                                            i.delete()
                                        messages.success(request, "Pin use completed", extra_tags='error')
                                        return HttpResponseRedirect(reverse('result:mark-entry'))
                                #else: return error saying wrong result for pin.
                                else:
                                    messages.success(request, f"Pin already registered for {checking.result.term.term} result", extra_tags='error')
                                    return HttpResponseRedirect(reverse('result:mark-entry'))
                            else:

templates/result/add-subject.html
{% extends 'base/base.html' %}
{% block content %}
  <div class="card">
    <div class="card-header">Subject Register Form</div>
    <div class="card-body">
      <form class="" action="" method="post">
        <div class="card">
          <div class="card-header">Subject Information</div>
          <div class="card-body">
            {% csrf_token %}
            {{ form.as_p }}
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Add Subject</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/result/mark-entry.html
{% extends 'base/base.html' %}
{% block content %}
<style type="text/css">

  #id_term {
        width: 90%;
      }

      #id_pin{
        width: 90%;
      }


      #label_term {
        width : 90%;
      }


      #label_pin {
        width : 90%;
      }





  @media screen and (min-width: 750px) {
      #id_term {
        width: 50%;
      }

      #label_term {
        width : 100%;
      }

      #label_pin {
        width : 100%;
      }

      #id_pin{
        width: 50%;
      }
    }


</style>
<div id="result_entry" class="card">
      <div class="card-header">
          <i class="fa fa-align-justify"></i>Select term to view result
    </div>


      <div class="card-body">
          {% if form.pin %}
        <form id="forms" method="post" action="{% url 'result:result-preview' %}">
            {% else %}
            <form id="forms" method="post" action="{% url 'result:student-mid-term-result' reg_no=request.user.user_student.all.0.student_persona.all.0.registration_no %}">
        {% endif %}

          <!-- <form id="forms" method="post" action=""> -->
        <div class="title">
          <i class="fas fa-pencil-alt"></i>
          {% csrf_token %}

          <h5><label id="label_term" style="margin: 2px;" for="id_term" class="perfect">Select Term:</label>
          {{ form.term }}</h5><br>
          {% if form.pin %}
          <h5><label id="label_pin" style="margin: 2px;" for="id_pin" class="perfect">Card Pin:</label>
          {{ form.pin }}</h5><br>
          {% endif %}
          <input type="hidden" name="year" id="year" value="{{ result.year }}">
          <input type="hidden" name="level" id="level" value="{{ result.level }}">
          <button class="btn btn-primary px-4" id="show_table">Submit</button>

        </div>
      </form>
      </div>
  </div>
  <strong>NOTE: </strong>
  <div style="color: red;">
    <p style="margin-bottom: 0rem;">Access PIN can only be used for one term only.</p>
    <p >PIN can be used for a maximum of 5 times.</p>
  </div>

{% endblock %}









{% block java %}
  <script>
      var term = document.querySelector('#id_term');
      var pin = document.querySelector('#id_pin');


      term.setAttribute('name', 'term');
      pin.setAttribute('name', 'pin');

      term.required = true;
      pin.required = true;







</script>
    {% endblock %}

templates/result/mark-entry1.html
{% extends 'base/base.html' %}
{% block content %}

<div id="result_entry" >




{% if result.coverpage %}

    <img style="width:100%;"  src="{{ result.coverpage.url }}" alt="result">

{% else %}

    <object data="{{ result.pdf.url }}#toolbar=0&navpanes=0&scrollbar=0&view=fitH" style="width:100%; height:1580px; line-height: 0px;" type="application/pdf">
      <span>Your web browser doesn't have a PDF plugin.
      Instead you can <a href="{% url 'result:download' level=result.clas term=result.term year=result.year %}">click here to
      download the PDF file.</a></span>
    </object>

{% endif %}


  </div>
{% endblock %}

templates/result/subject-list.html
{% extends 'base/base.html' %}
{% block content %}
  <div class="card">
    <div class="card-header"><i class="fa fa-align-justify"></i>Select Class</div>
    <div class="card-body">
      <form class="" action="" method="get">
        {% csrf_token %}
        {{ form.as_p }}
        <!-- <button type="submit" class="btn btn-primary">Go To Subject List</button> -->
        <input class="btn btn-success" type="submit" value="Submit" />
      </form>
    </div>
  </div>
  {% if subjects %}
  <div class="card">
      <div class="card-header">
          <i class="fa fa-align-justify"></i>Class List</div>
      <div class="card-body">
          <table class="table table-responsive-sm">
              <thead>
                  <tr>
                      <th>Id</th>
                      <th>Subject Name</th>
                      <th>Subject Code</th>
                      <th>Marks</th>
                      <th>Pass Marks</th>
                      <th>Action</th>
                  </tr>
              </thead>
              <tbody>
                  {% for sub in subjects %}
                    <tr>
                        <td>{{ sub.id }}</td>
                        <td>{{ sub.subject_name }}</td>
                        <td>{{ sub.subject_code }}</td>
                        <td>{{ sub.marks }}</td>
                        <td>{{ sub.pass_mark }}</td>
                        <td>
                          <a class="btn btn-success" title="Add Subject" href="{% url 'mark-table' sub.subject_name %}">
                              <i class="fa fa-search-plus"></i>
                          </a>
                          <a class="btn btn-info" title="View Subject List" href="">
                              <i class="fa fa-eye"></i>
                          </a>
                        </td>
                    </tr>
                  {% endfor %}
              </tbody>
          </table>
      </div>
  </div>
  {% endif %}
{% endblock %}