administration/urls.py
from django.urls import path
from . import views

app_name = 'administration'

urlpatterns = [
    path('login', views.admin_login, name='login'),
    path('logout', views.admin_logout, name='logout'),
    path('designation', views.add_designation, name='designation'),
    path('pin/', views.pincode_generated, name='pincode_generated'),
    path('pin-database/', views.pin_in_database, name='pin-database'),
    path('pin-allow/', views.pin_in_allow, name='pin-allow'),
]

result/urls.py
from django.urls import path, re_path

from .views import *


app_name = 'result'


urlpatterns = [
    path('add-subject', add_subject, name='add-subject'),
    path('subject-list', subject_list, name='subject-list'),
    path('mark-entry', mark_entry, name='mark-entry'),
    #path('mark-entry-mid-term', mark_entry_mid_term, name='mark-entry-mid-term'),
    path('result-preview', pin_check, name='result-preview'),
    #path('result-preview-mid-term', pin_check_mid_term, name='result-preview-mid-term'),
    re_path(r'mid-term-result/(?P<reg_no>[\w/]+)/$', student_mid_term_result, name="student-mid-term-result"),
    re_path(r'print/(?P<level>[\w-]+)/(?P<term>[\w\s\w]+)/(?P<year>[\w/]+)/$', print_write_pdf_view, name="print"),
    re_path(r'download/(?P<level>[\w-]+)/(?P<term>[\w\s\w]+)/(?P<year>[\w/]+)/$', download_write_pdf_view, name="download"),
    #path('print/<level>/<term>/<year>', print_write_pdf_view, name='print'),
    #path('download/<level>/<term>/<year>', download_write_pdf_view, name='download'),
    path('mark-table/<subject>', mark_table, name='mark-table'),

]

schoolmanagement/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .views import home_page, preview
import teacher.views as views
import student.views as student_views
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

import django.contrib.auth.views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('preview/', preview, name='preview'),
    path('', include('administration.urls')),
    #re_path(r'classroom-delete/(?P<class_name>[\w/]+)/$', views.create_class_delete, name="classroom-delete"),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('academic/', include('academic.urls')),
    path('employee/', include('employee.urls')),
    path('result/', include('result.urls')),
    path('address/', include('address.urls')),
    path('account/', include('account.urls')),
    path('attendance/', include('attendance.urls')),
    re_path(r'password_change/(?P<username>[\w/]+)/$', student_views.change_password, name="password_change"),
    #path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administration/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
import uuid
from django.urls import reverse
from django.db.models.fields import BLANK_CHOICE_DASH
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from academic.models import *

from django.core.validators import FileExtensionValidator

from pdf2image import convert_from_path
from django.conf import settings
import os





COVER_PAGE_DIRECTORY = 'coverdirectory/'
PDF_DIRECTORY = 'pdfdirectory/'
COVER_PAGE_FORMAT = 'jpg'





class Designation(models.Model):
    name = models.CharField(max_length=100, unique=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name



class PinCode(models.Model):

    reference           =       models.CharField(max_length=200, unique=True)
    created             =       models.DateTimeField(auto_now_add=True)
    updated             =       models.DateTimeField(auto_now=True)
    expiry_date             =       models.DateTimeField()

    class Meta:
    	ordering = ['-id']
    	verbose_name = 'Pin code'
    	verbose_name_plural = 'Pin codes'

    def __str__(self):
    	return self.reference


    def get_absolute_url(self):
    	return reverse("rscheck:first_page")



class ClassLevel(models.Model):

    class_level           =       models.CharField(blank=True, null=True, max_length=200)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Class level'
        verbose_name_plural = 'Class level'

    def __str__(self):
        return self.class_level


    def get_absolute_url(self):
        return reverse("rscheck:first_page")





class Number(models.Model):

	NUM = (
        (1,'1'),
        (2,'2'),
        (3,'3'),
        (4,'4'),
        (5,'5'),
        (6,'6'),
        (8,'8'),
        (9,'9'),
        (10,'10'),
        (11,'11'),
        (12,'12'),
        (13,'13'),
        (14,'14'),
        (15,'15'),
        (16,'16'),
        (18,'18'),
        (19,'19'),
        (20,'20'),)

	numbers          =      models.CharField(blank=True, null=True, max_length=10, choices=BLANK_CHOICE_DASH + list(NUM))
	created             =       models.DateTimeField(auto_now_add=True)
	updated             =       models.DateTimeField(auto_now=True)
	expiry_date             =       models.DateTimeField()


	class Meta:
		ordering = ['-id']
		verbose_name = 'Number'
		verbose_name_plural = 'Numbers'



	def __str__(self):
		return self.numbers



	def get_absolute_url(self):
		return reverse("rscheck:first_page")




class BoolMode(models.Model):

    name          =      models.CharField(blank=True, null=True, max_length=20)
    date = models.DateField(auto_now_add=True, blank=True, null=True)


    class Meta:
        ordering = ['-id']
        verbose_name = 'Bool Mode'
        verbose_name_plural = 'Bool Mode'



    def __str__(self):
        return self.name



    def get_absolute_url(self):
        return reverse("rscheck:first_page")







class PinAllow(models.Model):
    NUM = (
        ('True','True'),
        ('False','False'),)

    pin_allow          =      models.CharField(blank=True, null=True, max_length=10, choices=BLANK_CHOICE_DASH + list(NUM))
    date = models.DateField(auto_now_add=True, blank=True, null=True)


    class Meta:
        ordering = ['-id']
        verbose_name = 'Pin Allow'
        verbose_name_plural = 'Pin Allow'



    def __str__(self):
        return self.pin_allow



    def get_absolute_url(self):
        return reverse("rscheck:first_page")





class Term(models.Model):

    term  =  models.CharField(max_length=20)
    date = models.DateField(auto_now_add=True, blank=True, null=True)


    class Meta:
        ordering = ['-id']
        verbose_name = 'Term'
        verbose_name_plural = 'Terms'



    def __str__(self):
        return self.term



    def get_absolute_url(self):
        return reverse("rscheck:first_page")




class Year(models.Model):

    time           =       models.CharField(max_length=200)
    date = models.DateField(auto_now_add=True, blank=True, null=True)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Year'
        verbose_name_plural = 'year'

    def __str__(self):
        return self.time


    def get_absolute_url(self):
        return reverse("rscheck:first_page")






class StudentsInClass(models.Model):


    students = models.ManyToManyField(User, blank=True, related_name="class_joined")
    level    =   models.ForeignKey(ClassLevel, blank=True, null=True, on_delete=models.CASCADE, related_name="user_class")

    class Meta:
        ordering = ['-id']
        verbose_name = 'Students in class'
        verbose_name_plural = 'Students in class'



    def __str__(self):
        return self.students.username



    def get_absolute_url(self):
        return reverse("rscheck:first_page")


# this function is used to rename the pdf to the name specified by filename field
def set_pdf_file_name(instance):
    return os.path.join(PDF_DIRECTORY, '{}.pdf'.format(instance.pdf.name))



# not used in this example
def set_cover_file_name(instance):
    return os.path.join(COVER_PAGE_DIRECTORY, '{}.{}'.format(instance.pdf.name, COVER_PAGE_FORMAT))


class Result(models.Model):


    pdf = models.FileField(upload_to='pdfdirectory/', validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    coverpage  = models.ImageField(upload_to='coverdirectory/', null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_performance")
    clas    =   models.ForeignKey(ClassInfo, blank=True, null=True, on_delete=models.CASCADE, related_name="user_class_level")
    term =  models.ForeignKey(Term, on_delete=models.CASCADE, related_name="user_term_result", null=True, blank=True)
    year =  models.ForeignKey(Year, on_delete=models.CASCADE, related_name="user_year_result", null=True, blank=True)


    class Meta:
        ordering = ['-id']
        verbose_name = 'Result'
        verbose_name_plural = 'Result'



    def __str__(self):
        return self.user.username



    def get_absolute_url(self):
        return reverse("rscheck:first_page")


def convert_pdf_to_image(sender, instance, created, **kwargs):
    if created:
        #check if COVER_PAGE_DIRECTORY exists, create it if it doesn't
        #have to do this because of setting coverpage attribute of instance programmatically
        cover_page_dir = os.path.join(settings.MEDIA_ROOT, COVER_PAGE_DIRECTORY)

        if not os.path.exists(cover_page_dir):
            os.mkdir(cover_page_dir)

        # convert page cover (in this case) to jpg and save

        cover_page_image = convert_from_path(
            pdf_path=instance.pdf.path,
            dpi=200,
            first_page=1,
            last_page=1,
            fmt=COVER_PAGE_FORMAT,
            output_folder=cover_page_dir,
        )[0]


        # get name of pdf_file
        pdf_filename, extension = os.path.splitext(os.path.basename(instance.pdf.name))
        new_cover_page_path = '{}.{}'.format(os.path.join(cover_page_dir, pdf_filename), COVER_PAGE_FORMAT)
        # rename the file that was saved to be the same as the pdf file
        os.rename(cover_page_image.filename, new_cover_page_path)
        # get the relative path to the cover page to store in model
        new_cover_page_path_relative = '{}.{}'.format(os.path.join(COVER_PAGE_DIRECTORY, pdf_filename), COVER_PAGE_FORMAT)
        instance.coverpage = new_cover_page_path_relative

        # call save on the model instance to update database record
        instance.save()

post_save.connect(convert_pdf_to_image, sender=Result)






# class StudentsBio(models.Model):


#     user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_bio")
#     clas    =   models.ForeignKey(ClassLevel, blank=True, null=True, on_delete=models.CASCADE, related_name="user_class_bio")
#     term =  models.ForeignKey(Term, on_delete=models.CASCADE, related_name="user_term_result", null=True, blank=True)
#     year =  models.ForeignKey(Year, on_delete=models.CASCADE, related_name="user_year_result", null=True, blank=True)


#     class Meta:
#         ordering = ['-id']
#         verbose_name = 'Performance'
#         verbose_name_plural = 'Performance'



#     def __str__(self):
#         return self.user.username



#     def get_absolute_url(self):
#         return reverse("rscheck:first_page")


class PinCodeTime(models.Model):

    reference           =       models.CharField(max_length=200, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_result")
    result = 	models.ForeignKey(Result,  blank=True, null=True, on_delete=models.CASCADE, related_name="pin_connect_result")


    class Meta:
        ordering = ['-id']
        verbose_name = 'Pin Code Time'
        verbose_name_plural = 'Pin Codes Time'

    def __str__(self):
        return self.user.username


    def get_absolute_url(self):
        return reverse("rscheck:first_page")




class Administration(models.Model):


    term =  models.ForeignKey(Term, on_delete=models.CASCADE, related_name="new_term_result", null=True, blank=True)


    class Meta:
        ordering = ['-id']
        verbose_name = 'Administration'
        verbose_name_plural = 'Administration'



    def get_absolute_url(self):
        return reverse("rscheck:first_page")




class CurrentSession(models.Model):
	name = models.ForeignKey(Year, on_delete=models.CASCADE, related_name="admin_current_session")
	begining_date = models.DateField(auto_now_add=True, blank=True, null=True)
	end_date = models.DateTimeField(blank=True, null=True)







class CurrentTerm(models.Model):
    name = models.ForeignKey(Term, on_delete=models.CASCADE, related_name="admin_current_term")
    begining_date = models.DateField(auto_now_add=True, blank=True, null=True)

administration/forms.py
from django import forms
from teacher import models
from .models import *





class AdminLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))


# class AddDepartmentForm(forms.ModelForm):
#     class Meta:
#         model = models.Department
#         fields = '__all__'
#         widgets = {
#             'name': forms.TextInput(attrs={'class': 'form-control'}),
#         }
# class AddDesignationForm(forms.ModelForm):
#     class Meta:
#         model = models.Designation
#         fields = '__all__'
#         widgets = {
#             'name': forms.TextInput(attrs={'class': 'form-control'}),
#         }



class UserLoginForm(forms.Form):
    username = forms.CharField(label="", widget= forms.TextInput())
    password = forms.CharField(label="", widget=forms.PasswordInput())
    #pin = forms.CharField(label="", widget=forms.PasswordInput())


class NumberOfPin(forms.ModelForm):
    class Meta:
        model = Number
        fields = (
            'numbers',
            'expiry_date',
            )


class AllowPinForm(forms.ModelForm):
    class Meta:
        model = PinAllow
        fields = (
            'pin_allow',
            )

templates/administration/dashboard.html
{% extends 'administration/base1.html' %}

{% block title %}
<title>Dashboard|Result</title>

{% endblock %}




{% block content %}



<div style="line-height: 0;" class="container-fluid">
  <div class="row">
    <!-- <span class="profile" data-icon="carbon:user-profile" data-inline="false"></span> -->
    <nav style="background-color: #22292e;" id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse"> <span id="profile" class="iconify" data-icon="carbon:user-profile" data-inline="false" data-height="4.5em"></span>

        <ul class="nav flex-column">
          <li style="width: 25%; background-color: black;" class="nav-item">
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="#">
              <h6>Registration Number:</h6><br><span></span><p>03/1642</p> <!-- <p>{{ result.user.username|capfirst }}</p> -->
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <h6>Name:</h6> <p>FAKOYA , PATRICK <!-- {{ result.user.last_name|upper }} {{ result.user.first_name|upper }} --></h6></p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
             <h6>Current Session:</h6> <p>2019 / 2020 <!-- {{ result.year.time }} --></h6></p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <!-- <span data-feather="bar-chart-2"></span> -->
              <h6>Current Term:</h6> <p>2ND TERM <!-- {{ result.term.term|upper }} --></h6></p>
            </a>
          </li>

          <div>

          <li class="nav-item">
            <a class="nav-link" href="#">
              <hr><br>
              
              <button class="btn btn-sm btn-outline-secondary">
                Print <span class="iconify" data-icon="fluent:print-48-filled" data-inline="false"></span>
              </button><hr>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <button class="btn btn-sm btn-outline-secondary">
                Download <span class="iconify" data-icon="el:download-alt" data-inline="false"></span>
              </button><hr>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'administration:logout' %}">
              <button class="btn btn-sm btn-outline-secondary">
                Sign out <span class="iconify" data-icon="uil:signout" data-inline="false"></span>
              </button><hr>
            </a>
          </li>
          </div>
          
        </ul>

        
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      {% if result %}
    <p>
    <iframe src="{{ result.pdf.url }}#toolbar=0&navpanes=0&scrollbar=0&view=fitH" style="width:100%; height:1500px; line-height: 0px;" frameborder="0"> Your browser should support iFrame to view this PDF document</iframe>
  </p>
  {% else %}
  <p>No result to show</p>
  {% endif %}

    </main>
  </div>
</div>


    
    {% endblock %}

templates/administration/designation.html
{% extends 'base/base.html' %}
{% block content %}
  <div class="card">
    <div class="card-header">Designation Register Form</div>
    <div class="card-body">
      <form class="" action="" method="post">
        {% csrf_token %}
        {{ forms.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>

  <div class="card">
      <div class="card-header">
          <i class="fa fa-align-justify"></i>Designation List</div>
      <div class="card-body">
          <table class="table table-responsive-sm">
              <thead>
                  <tr>
                      <th>Id</th>
                      <th>Designation Name</th>
                      <th>Register Date</th>
                  </tr>
              </thead>
              <tbody>
                  {% for designation in designation %}
                    <tr>
                        <td>{{ designation.id }}</td>
                        <td>{{ designation.name }}</td>
                        <td>{{ designation.date }}</td>
                    </tr>
                  {% endfor %}
              </tbody>
          </table>
      </div>
  </div>
{% endblock %}

templates/administration/pin-allow.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Result Checking Application {% endblock %}
{% block content %}


{% if term|length  > 0 %}
{% if current_term|length  > 0 %}




<marquee behavior="" direction="">Change Current Term</marquee>
<div class="animated fadeIn">
  <div class="row">
    <div class="col-sm-6 col-lg-6">
      <div class="card text-white bg-primary">


        <style type="text/css">
          label {
          display: flex;
          }

          @media screen and (min-width: 536px) {
          label {
          width: 10%;
          display: inline-block;
          }
          }
        </style>



        {% if forms.errors %}
        {% for field in forms %}
        {% for error in field.errors %}
        <div>
          <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in forms.non_field_errors %}
        <div>
          <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endif %}









        <div class="card">
          <div class="card-header">Select</div>
            <div class="card-body">
              <form class="" action="" method="post" enctype="multipart/form-data" id="StudentRegistrationForm" data-upazilla-url="{% url 'load-upazilla' %}">
                <div class="academic_info">

                  <div class="card-body">
                  {% csrf_token %}


                    <span style='color: black;'>Select:</span>
                    {{ forms.name }}


                  </div>
                  <button id="create_class" type="submit" class="btn btn-primary pull-left">Save</button>
                </div>
              </form>
            </div>
</div>


</div>
</div>

<div class="col-sm-8 col-lg-4">

<table class="table table-striped table-bordered datatable dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info" style="border-collapse: collapse !important">
<thead>
<tr role="row">
<th>CURRENT TERM</th>
</tr>
</thead>
<tbody>
{% for term in current_term %}








<tr role="row" class="odd">
<td>{{ term.name|upper }}</td>






</tr>
{% endfor %}
</tbody>
</table>






</div>

</div>
</div>

{% else %}

<marquee behavior="" direction="">Choose Current Term</marquee>
<div class="animated fadeIn">
<div class="row">
<div class="col-sm-6 col-lg-6">
<div class="card text-white bg-primary">


<style type="text/css">
label {
display: flex;
}

@media screen and (min-width: 536px) {
label {
width: 10%;
display: inline-block;
}
}



</style>



{% if forms1.errors %}
{% for field in forms1 %}
{% for error in field.errors %}
<div>
<strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endfor %}
{% for error in forms1.non_field_errors %}
<div>
<strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endif %}









<div class="card">
<div class="card-header">Select Current Term Below</div>
<div class="card-body">
<form class="" action="" method="post" enctype="multipart/form-data" id="StudentRegistrationForm" data-upazilla-url="{% url 'load-upazilla' %}">
<div class="academic_info">

<div class="card-body">
{% csrf_token %}


<span style='color: black;'>Select:</span>
{{ forms.name }}


</div>
<button id="create_class" type="submit" class="btn btn-primary pull-left">Save</button>
</div>
{% endif %}

{% else %}



<marquee behavior="" direction="">Term Not Created</marquee>


{% endif %}








{% endblock %}


{% block java %}

 <script>

     var name1 = document.querySelector('#id_name');



$(document).ready(function() {
$('#id_name').blur(function(e){
    e.preventDefault();
    var val = $(this).val();
    var final =removeSpaces(val);
    $(this).val(final);


    function removeSpaces(string) {
     return string.split(' ').join('');
    }
});


});










$(document).ready(function() {
    var class_name1;
    $('.class_name').click(function(e){
        e.preventDefault();
        class_name1 = $(this).attr("data-class");
        console.log(class_name1)
        /*var action = $('#a_form').attr('action', `http://127.0.0.1:8000/teacher/create-classroom-edit/`);*/
        saveans();
    });




    function saveans(){
        $.ajax({
            type: 'POST',
            url: "{% url 'create-classroom' %}",
            headers: {'X-CSRFToken': csrftoken},
            data : {
              "class_name": class_name1
            },
            dataType: 'json',
            success: function(data){
              console.log(data.form)
              $('#edit-form').html(data.form);
            }
        });
        return false;
    }



    function getCookie(name){
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
              const cookie = cookies[i].trim();
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');




});





</script>
{% endblock %}

templates/administration/pin-preview.html
{% extends 'base/base.html' %}







{% block content %}

<h3>Pin Generated</h3>

<div  class="row">
  <div style="overflow-x: auto;" class="col-sm-12">
      <table class="table table-striped table-bordered datatable dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info" style="border-collapse: collapse !important">
          <thead>
              <tr role="row">
                  <th>Id</th>
                  <th>Pin</th>
              </tr>
          </thead>
          <tbody>
              {% for i in paragraphs %}
              <tr role="row" class="odd">
                  <td>{{ forloop.counter }}</td>
                  <td>{{ i }}</td>
                </tr>
              {% endfor %}
          </tbody>
      </table>
  </div>
</div> 





{% endblock %}

templates/administration/pin.html
<!DOCTYPE html>
<!--
* CoreUI - Free Bootstrap Admin Template
* @version v2.1.12
* @link https://coreui.io
* Copyright (c) 2018 creativeLabs Łukasz Holeczek
* Licensed under MIT (https://coreui.io/license)
-->

<html lang="en">
  <head>
    <link href="node_modules/@coreui/icons/css/coreui-icons.min.css" rel="stylesheet">
    <link href="node_modules/flag-icon-css/css/flag-icon.min.css" rel="stylesheet">
    <link href="node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="node_modules/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">
    <!-- Main styles for this application-->
    <link href="css/style.css" rel="stylesheet">
    <link href="vendors/pace-progress/css/pace.min.css" rel="stylesheet">
    <!-- Global site tag (gtag.js) - Google Analytics-->
    <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-118965717-3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];

      function gtag() {
        dataLayer.push(arguments);
      }
      gtag('js', new Date());
      // Shared ID
      gtag('config', 'UA-118965717-3');
      // Bootstrap ID
      gtag('config', 'UA-118965717-5');
    </script>
    {% include 'base/header.html' %}
    <style type="text/css">
      #id_numbers {
        width: -webkit-fill-available;
      }

      #id_expiry_date {
        width: -webkit-fill-available;
      }
    </style>
  </head>
  <body class="app flex-row align-items-center">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <div class="card-group">
            <div class="card p-4">
              <div class="card-body">
                <h1>Generate Pin</h1>
                <form class="" action="" method="post">
                  {% csrf_token %}
                    <!-- <div class="input-group mb-3"> -->
                      <div>
                        <!-- <div class="input-group-prepend"> -->
                          <div>
                            <!-- <span class="input-group-text">
                                <i class="icon-user"></i>
                            </span> -->
                        </div>
                        Select Number:
                        {{ forms.numbers }}<br><br>

                        Expiry Date:
                        {{ forms.expiry_date }}<br>
                        <br>
                    </div>
                  <div class="row">
                    <div class="col-6">
                      <button class="btn btn-primary px-4">Generate</button>
                       <!-- <input type="submit" value="Generate" class="btn btn-primary px-4" /> -->
                    </div>
                    <!-- <div class="col-6 text-right">
                      <button class="btn btn-link px-0" type="button">Forgot password?</button>
                    </div> -->
                  </div>
                </form>
              </div>
            </div>
            <div class="card text-white bg-primary py-5 d-md-down-none" style="width:44%">
              <div class="card-body text-center">
                <div>
                  <h2>Go back to hompage</h2>
                      <a style="color:white; background-color: #0a63c2; border-color: #0a63c2;" class="btn btn-primary px-4" href="{% url 'home' %}">Homepage</a>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- CoreUI and necessary plugins-->
    {% include 'base/js.html' %}
     <script>
        var numbers = document.querySelector('#id_numbers');
        var expiry_date = document.querySelector('#id_expiry_date');

        numbers.setAttribute('name',"num");
        numbers.setAttribute('class', 'fname');

        expiry_date.setAttribute('name',"expiry_date");
        expiry_date.setAttribute('class', 'fname');

        numbers.name = 'num';

        numbers.required = true;
        expiry_date.required = true;
        expiry_date.name = 'expiry_date';
        expiry_date.type = 'date';

  </script>



  </body>
</html>